### ISSUE TITLE
Warning with _xenomai_init_fetchargv in bootstrap-template.h

### ISSUE THREAD

**Issue by vdehors** [nolange/cmake_xenomai#3]
Hi, I compiled a simple HelloWorld using the patchset (Xenomai 3.1) with the following config :

* COBALT
* _XENOMAI_BOOTSTRAP_GLIBC_CONSTRUCTORS_REAL = 1
* _XENOMAI_INIT_HASFETCHARGV not defined

In this case, the static inline function `_xenomai_init_fetchargv()` is declared but not defined. I think the declaration should be moved just before the definition of `xenomai_bootstrap()` only in the case _XENOMAI_BOOTSTRAP_GLIBC_CONSTRUCTORS_REAL != 1.

Do you want a PR ? If yes, which headers do I have to change (there are three bootstrap-template.h in the repository)

**Comment by nolange** [comment]
I horribly neglected this repository, I still want to do a big cleanup, potentially after 3.1 is released. So a PR is not worth it for now.

I also have a local version, that I have not pushed yet, see if this fixes your problem:

```patch
@@ -109,7 +109,8 @@ int _XENOMAI_BOOTSTRAP_DEFINE_MAINWRAPPER(int argc, char *const argv[]);
 
 #if defined(_XENOMAI_INIT_HASFETCHARGV)
 #define _xenomai_init_fetchargv(a, v) xenomai_init_fetchargv((a), (v))
-#else
+#elif  (!defined(_XENOMAI_BOOTSTRAP_GLIBC_CONSTRUCTORS_REAL) || \
+        _XENOMAI_BOOTSTRAP_GLIBC_CONSTRUCTORS_REAL != 1)
 __attribute__((unused,always_inline))
 static __inline__ int _xenomai_init_fetchargv(int *argcp, char *const **argvp);
 #endif
```

**Comment by vdehors** [comment]
Ok, seems good thanks !
